amazon-braket/amazon-braket-pennylane-plugin-python

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/publish-to-pypi.yml, .github/workflows/stale_issue.yml, README.rst, setup.py
Also added issue templates, stale issue workflow and badges
=> infra: Auto-publish to PyPi

README.rst
=> infra: Fix link formatting in README

README.rst
=> infra: Add build badge

.github/workflows/python-package.yml, README.rst, tox.ini
=> infra: Enable Codecov

doc/devices/braket_local.rst, doc/devices/braket_remote.rst, src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/test_apply.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_ops.py
NA
Added mapping between inverse gates and their inverses, as well as mapping for translating parameters from pennylane to braket, specifically in the case of inverse operations
unit tests added
=> feature: support operation inverses

README.rst, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/test_apply.py, test/unit_tests/test_braket_device.py
=> change: Add inverses to integ tests

CODEOWNERS, src/braket/pennylane_plugin/ops.py, test/unit_tests/test_ops.py
=> feature: Decompositions of XY and Ising gates

.github/workflows/python-package.yml, test/unit_tests/test_braket_device.py, tox.ini
Also updates python-package workflow to run tests with the main branch
of dependencies instead of latest releases.
=> infra: Update tests for AwsDevice implementation

setup.py
Updates the `setup.py` file to ease the PennyLane version pinning. This allows the Braket plugin to work with the development version of PennyLane.
=> change: Update setup.py to ease PennyLane pinning

doc/devices/braket_local.rst, doc/devices/braket_remote.rst
=> documentation: Correct supported gates

.github/workflows/python-package.yml, README.rst, doc/conf.py, doc/devices/braket_local.rst, doc/devices/braket_remote.rst, doc/index.rst, setup.py, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/conftest.py, test/integ_tests/test_apply.py, test/integ_tests/test_integration.py, test/integ_tests/test_state.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_translation.py, tox.ini
Add support for upcoming Braket density matrix simulators. This PR will not be submitted until these density matrix simulators are ready.
Unit tests and integration tests. Also ran through a few PennyLane notebooks.
=> feature: Support for density matrix simulators

src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_braket_device.py
update: Make supported operations device specific
Unit tests with two devices pass with the existing operations
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, …
=> update: Make supported operations device specific

example.py, setup.py, src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/_version.py, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/conftest.py, test/integ_tests/test_apply.py, test/integ_tests/test_batch.py, test/integ_tests/test_expval.py, test/integ_tests/test_integration.py, test/integ_tests/test_sample.py, test/integ_tests/test_state.py, test/integ_tests/test_var.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py
=> fix: correct operation names

setup.py, src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py
Add isingYY support as part of PennyLane-0.17 release
Changed ops for YY gate to qml.IsingYY
Updated unit tests
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, …
=> feature: Add IsingYY support

src/braket/pennylane_plugin/braket_device.py, test/unit_tests/test_braket_device.py
#74 
This PR adds [Tracker](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.Tracker.html) support, as its added to PennyLane in the upcoming v0.17.0 .
The `pl-device-test` plugin tests from PennyLane core check "standard" Tracker usage.  As hopefully the bracket plugin will provide more information, we may need to provide additional tests.
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIB …
=> Add Device Tracker Support

test/integ_tests/test_batch.py
Fixing tests for PL-0.20. Need to change the tests for torch and tensorflow, but those are skipped anyways.
All tests passed.
=> fix: integ tests for PL-0.20

test/integ_tests/conftest.py, test/integ_tests/test_apply.py, test/integ_tests/test_sample.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_ops.py
=> fix: fix auto formatting

test/integ_tests/test_tracking.py
=> fix: Fix device tracker integ test for PennyLane 0.21

setup.py
fix: Pin pennylane version
tox
=> fix: Pin pennylane version

test/integ_tests/test_batch.py
- Fixes integration tests for tensorflow and torch libraries after breaking changes introduced in PL-0.20. 
tox with libraries installed 
=> fix: integ tests for TF, Torch for PL>0.20

setup.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/test_apply.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py
#87 
- Handling breaking changes for pennylane 
- Fix deprecated items 
- tox
=> fix: pennylane breaking changes

src/braket/pennylane_plugin/ops.py, test/unit_tests/test_ops.py
=> update: fix ECR definition

test/unit_tests/test_ops.py
=> update: unit-test for ECR gate

src/braket/pennylane_plugin/braket_device.py
=> Update deprecated imports for version 0.23

test/integ_tests/test_apply.py
=> infra: Fix integ test imports

setup.py, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_braket_device.py
Upgrade code to reference OpenQASM over Jaqcd
unit and integ tests passing
=> feature: use OpenQASM for device property validation

src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py, tox.ini
Add GPi gate with numerical differentiation method
Unit testing and manual
=> feature: gpi gate

src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py
=> feature: add gpi2 gate

src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py
=> feature: MS gate

setup.py, src/braket/pennylane_plugin/translation.py
use supportedPragmas to validate noise ops
unit tests and manual circuit run with BitFlip
=> fix: use supported pragmas to validate noise

setup.py, src/braket/pennylane_plugin/__init__.py, src/braket/pennylane_plugin/ops.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_ops.py, test/unit_tests/test_translation.py, tox.ini
Add native gates for IonQ
Manual and unit tests
=> feature: IonQ native gates

src/braket/pennylane_plugin/translation.py, test/unit_tests/test_translation.py
Add identity operation to plugin
unit tests
=> feature: add identity operation

.github/workflows/publish-to-pypi.yml, .github/workflows/python-package.yml, README.rst
https://github.com/badges/shields/issues/8671
https://github.com/aws-samples/amazon-braket-algorithm-library/commit/40bf548380c56ce4fa95f88e5071ca532a677701
=> infra: update github workflows for node12 retirement

.github/workflows/python-package.yml, .readthedocs.yml, README.rst, setup.py
=> deprecation: deprecate python 3.7

setup.py
autoray update broke PennyLane
https://github.com/PennyLaneAI/pennylane/issues/3867
pin autoray
GH Actions unit tests
=> fix: pin autoray

doc/devices/braket_local.rst, doc/devices/braket_remote.rst, src/braket/pennylane_plugin/ops.py
=> doc: Correct supported operations

README.rst
*Issue #, if available:* N/A
*Description of changes:* Add a reference to the Quantum Computing Stack Exchange.
=> documenation: Update README support info

.github/workflows/python-package.yml, CHANGELOG.md, setup.cfg, setup.py, src/braket/pennylane_plugin/_version.py, tox.ini
=> Merge main into pl30

README.rst
=> doc: Correct README format for PyPI

src/braket/pennylane_plugin/braket_device.py, test/integ_tests/test_adjoint_gradient.py, test/unit_tests/test_braket_device.py
=> fix: Adjoint gradient active return compatibility

test/unit_tests/test_braket_device.py, tox.ini
=> fix: update the project name for coverage runs and clean the tox env

setup.cfg, setup.py, src/braket/pennylane_plugin/ahs_device.py, src/braket/pennylane_plugin/braket_device.py, tox.ini
=> docs: add a linter to check proper rst formatting and fix up incorrect docs

.github/workflows/twine-check.yml
=> infra: Don't run twine check on push

test/integ_tests/test_shadow_expval.py
=> fix: temporarily disabling integ test.

test/integ_tests/test_shadow_expval.py
Ran the new configuration for this test. It should be expected to fail only a few times in a million trials now.
=> test: increase shots and skip SV1 on shadow test

test/integ_tests/conftest.py, test/integ_tests/test_state.py
locally run all unit and integ tests
=> test: add braket_dm to local devices for testing

setup.py
=> fix: constrain tensorflow version

setup.py
=> Update pennylane version constraint

src/braket/pennylane_plugin/ops.py
* Updated default value of `do_queue` to account for changes in the upcoming release. See [this](https://github.com/PennyLaneAI/pennylane/commit/5a9fd249b717dae80ec7f48dd2efe57deee38188#diff-ed5f9c0de17892f74e5119e2a032fe277eaa330ec4df0c249c7a75af7be6585eR432) for details. 
=> fix: set do_queue default to None

CODEOWNERS
=> infra: Update CODEOWNERS

src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_translation.py
Run circuits using a device's native gate set
Manually verified on multiple qpus and added unit tests
=> feat: native mode

README.rst
=> docs: update README to recommend using Python 3.8

src/braket/pennylane_plugin/braket_device.py, test/unit_tests/test_braket_device.py
=> fix: Don't create `FreeParameter`s for noise

.github/dependabot.yml
=> infra: Update dependabot to use the `infra:` prefix

src/braket/pennylane_plugin/ops.py
=> Extract tf casting function

.github/pull_request_template.md, CONTRIBUTING.md, README.rst, doc/index.rst, setup.py, tox.ini
*Description of changes:*-
Updated urls to amazon-braket github org from aws
Local unit and integ tests
=> doc: update for amazon-braket org

README.rst
=> doc: Replace aws org with amazon-braket in badges

.pre-commit-config.yaml, tox.ini
=> infra: add read only linter precommit hook

doc/conf.py
1. The field used to define the name of the plugin for the sidebar was using an old format. Compare the rendered plugin page for the Qiskit plugin (see plugin name top-left):
to the one for the Amazon Braket plugin:
Updating the name of this field will cause the name of the plugin to render correctly.
2. Updating the name of the Google Analytics tracking ID field according to the requirements for this version of Sphinx.
EDIT: A few of the other html build options are actually deprecated, and are causing the nave bar not to render properly. The minimal html navbar options have been included, matching what is configured for the other PennyLane Plugin docs pages.
Follows the values as defined for the other plugin pages on …
=> doc: Update conf.py

.github/workflows/python-package.yml, .readthedocs.yml, README.rst, setup.py
=> feat: remove python 3.8 support

src/braket/pennylane_plugin/ahs_device.py, src/braket/pennylane_plugin/ahs_translation.py, src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/integ_tests/test_shadow_expval.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_shadow_expval.py
=> doc: Use builtins for type hints

.github/workflows/check-format.yml, .github/workflows/twine-check.yml
=> infra: limit check format imports

setup.cfg
=> infra: add better profiling for unit tests

tox.ini
=> infra: have the PL tests use the latest schemas and default-sim codes

.github/workflows/publish-to-pypi.yml
=> infra: install setuptools for pypi publishing

tox.ini
=> infra: set the default simulator and schemas as first in order for test-deps

.github/workflows/check-format.yml
=> fix: use the linter checks for code formatting

README.rst
=> doc: minor change to tox instructions

src/braket/pennylane_plugin/translation.py, test/unit_tests/test_translation.py
=> fix: Raise a `DeviceError instead of `TypeError`

setup.py
So many versions of `pylint` are downloaded for dependency resolution. This will limit that number
=> infra: add lower constraint to pylint

src/braket/pennylane_plugin/braket_device.py
=> fix: Let PennyLane handle `SProd` and `Sum`

src/braket/pennylane_plugin/braket_device.py
=> fix: Correct comment

setup.py
=> infra: update TF version

setup.py
=> fix: Update autoray to >= 0.6.11

setup.py
=> infra: update torch constraints for testing

doc/devices/braket_local.rst, src/braket/pennylane_plugin/braket_device.py, test/integ_tests/test_batch.py, test/unit_tests/test_braket_device.py
*Issue #, if available:* N/A
*Description of changes:* Moves `batch_execute` up to the `BraketQubitDevice` super-class and gives its child-classes `BraketAwsQubitDevice` and `BraketLocalQubitDevice` specific internal methods to run batches of PL circuits. Adds unit and integration tests as well as a doc update for these changes. This allows `BraketLocalQubitDevice` to successfully execute batches and not throw an error if the device is created with `parallel=True` or `parallel=False`.
*Testing done:* Unit and integration tests passed locally.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull …
=> feat: Support `batch_execute` for `BraketLocalQubitDevice`

src/braket/pennylane_plugin/ahs_device.py, test/unit_tests/test_ahs_device.py
=> test: Compatibility with `LegacyDeviceFacade`

setup.py, test/integ_tests/test_ahs_device.py, test/integ_tests/test_integration.py, test/unit_tests/test_ahs_device.py
=> test: Integ compatibility with LegacyDeviceFacade

src/braket/pennylane_plugin/braket_device.py, src/braket/pennylane_plugin/translation.py, test/unit_tests/device_property_jsons.py, test/unit_tests/test_braket_device.py, test/unit_tests/test_shadow_expval.py
=> feat: Device-specific supported observables

setup.py
This can be unpinned once the new PL version is released. Track the fix deploying in https://github.com/PennyLaneAI/pennylane/commit/48bc1d1af93a54e1b3ab8dc9905d395d59d8af21
=> infra: constrain autoray

setup.py
Will unpin once #285 has been fixed
=> fix: Pin PL <0.40

README.rst, pyproject.toml, setup.py
=> change: Update linters to Python 3.10

.readthedocs.yml
=> doc: Unquote python latest for docs
