src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_ops.py
test/unit_tests/test_translation.py

*Description of changes:* A new version (0.14.0) of PennyLane will shortly be released that makes [tape mode](https://pennylane.readthedocs.io/en/stable/code/qml_tape.html) the default core. This means that the `qml.CircuitGraph` is replaced with a `QuantumTape`, and we also work with a new `QNode`.
A side effect of this change is that returning `qml.probs()` is incompatible with the Braket device when using the new PL core. Indeed, we are now hitting [this](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/0995d01c6de6f042cf64c3c428b0d46fd7e4c68a/src/braket/pennylane_plugin/translation.py#L247) exception.
This is because `qml.probs()` is now more generally a [MeasurementProcess](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.tape.MeasurementProcess.html) - …

Fix probability returns

---

src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

*Description of changes:* In PL-core, it is possible for `wires` to be a list of strings and/or numbers:
```python
import pennylane as qml
dev = qml.device("default.qubit", wires=["a", -1])
@qml.qnode(dev)
def f(x):
qml.RX(x, wires="a")
qml.RZ(x, wires=-1)
return qml.expval(qml.PauliZ("a") @ qml.PauliZ(-1))
f(0.3)
```
This PR extends support to the Braket device.
*Testing done:* A `test_wires` test has been added. Furthermore, we have added the `braket.local.qubit` device to the [PL testing matrix](https://github.com/PennyLaneAI/plugin-test-matrix#testing-matrix). Here, the device is tested against the [standard device test suite](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/devices/tests). It was the failures there within the `test_wires.py` file that made us notice …

Improved wires support

---

setup.py
src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

Adds two unit tests to boost coverage to 100%. This ensures that any future PRs that are fully covered but drop the total SLOC don't fail codecov/project due to the drop in total coverage %. Note: PL version has been fixed to 0.14.1 for compatibility.

infra: Crank up coverage to 100%

---

src/braket/pennylane_plugin/ops.py
test/unit_tests/test_ops.py

Corrected the XY gate to use the four-term rule introduced in https://arxiv.org/abs/2104.05695. Added unit tests to ensure correctness of parameter shift rules.

fix: Correct parameter-shift rules

---

doc/devices/braket_local.rst
doc/devices/braket_remote.rst
doc/xanadu_theme/header.html
doc/xanadu_theme/layout.html
doc/xanadu_theme/static/xanadu.css_t
setup.py
src/braket/pennylane_plugin/_version.py
src/braket/pennylane_plugin/braket_device.py
test/integ_tests/test_batch.py
test/integ_tests/test_expval.py
test/integ_tests/test_integration.py
test/integ_tests/test_var.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

Fixes https://github.com/aws/amazon-braket-pennylane-plugin-python/issues/61.
*Context:*
A new version of PennyLane is planned for release next week. This version includes some [changes](https://pennylane.readthedocs.io/en/latest/development/release_notes.html) that impact the Braket-PennyLane device, including:
- The `analytic` keyword argument for devices has been removed. Now, `shots=None` indicates analytic mode. ([PR](https://github.com/PennyLaneAI/pennylane/pull/1079))
- The new Tape-based core is now the default and the old core has been remove ([PR](https://github.com/PennyLaneAI/pennylane/pull/1100)). Consequently, `qml.enable_tape()` is no longer available and should be removed.
The [plugin test …

Fix Braket-PennyLane plugin in preparation for PennyLane v0.15.0 release

---

setup.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/integ_tests/test_expval.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

Adds support for direct evaluation of Hamiltonian expectation values
when `shots=None`; instead of running a circuit for each term or QWC
group, the expectation value can be calculated with one circuit.

feature: Support for Hamiltonians

---

src/braket/pennylane_plugin/braket_device.py
test/integ_tests/test_integration.py

- s3_destination folder should not be a mandatory parameter for pennylane notebooks, default bucket is used/created if s3 details are not provided by the customer.
tox, tested submitting task without bucket details provided.

change: make s3_bucket optional

---

doc/requirements.txt
setup.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_translation.py

https://github.com/aws/amazon-braket-pennylane-plugin-python/issues/96
Changed the import of ObservableReturnTypes to the measurements module.
tox

fix: fixing change of location of ObservableReturnTypes

---

test/unit_tests/test_braket_device.py

The new numpy v1.24.0 now does not allow inhomogeneous numpy array. One unit test in this repo fails for this reason. This PR fixes that unit test. 
tox

fix: remove inhomogeneous numpy array

---

setup.py
test/unit_tests/test_braket_device.py

Pennylane released v0.28 on Monday. This new version causes some unit tests to fail. Capping the Pennylane version at v0.27.0 for now.
tox

cap pennylane version at v0.27

---

src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

Fixes #129 by establishing a code path for running circuits with trainable parameters and either variance measurements or multiple observables when shots=0.

fix: `shots=0` measurements with trainable params

---

README.rst
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

Sends fewer input parameters to the service, and also improves translation speed my only iterating over operation list once.

Only include trainable parameters in `inputs`

---

src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

With version `v0.30` of PennyLane, the new return types specification in enabled by default. Instead of forcing results into a ragged numpy array, devices, QNodes, and everything in between use tuples of information instead.
For example:
```
@qml.qnode(qml.device('braket.local.qubit', wires=n_wires), diff_method=None)
def circuit():
return qml.expval(qml.PauliZ(0)), qml.probs()
circuit()
```
```
(array(1.), array([1., 0., 0., 0.]))
```
Local unit tests pass.  The `pl-device-test` also passes with the local simulator.
Integration tests with remote simulator or hardware have not yet been run due to difficulties configuring the aws profile.
I can add more local tests for multiple measurements, as most tests cases on the plugin currently only test for …

Make plugin compatible with new return types specification

---

src/braket/pennylane_plugin/braket_device.py
test/integ_tests/test_shadow_expval.py
test/unit_tests/test_shadow_expval.py

*Issue #, if available:* N/A
Add support for Braket devices (local and remote) to compute [expectation values](https://pennylane.ai/qml/demos/tutorial_diffable_shadows.html) with the [classical shadows](https://pennylane.ai/qml/demos/tutorial_classical_shadows.html) technique. 
The implementation is a little weird because we have to work around how the current PL device API "expects" plugins to interact with the `ShadowExpvalMP` transform. Each snapshot is a single-shot run so for remote devices, we can use batching to speed up the computation.
Basic integration tests added. Very open to suggestions.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

feature: implement support for classical shadows and computing expectation values with them

---

test/integ_tests/test_shadow_expval.py

*Issue #, if available:* N/A
*Description of changes:* Lowered the shot count to 1000 and loosened tolerances.
*Testing done:* Integ test passed locally.

fix: Lower shot count on shadow_expval integ test so it can finish

---

src/braket/pennylane_plugin/translation.py
test/unit_tests/test_ahs_device.py
test/unit_tests/test_braket_device.py

The plugin is currently not working with the new version of `qml.Projector` that was released with PennyLane 0.31, as we saw with the [last version updates](https://github.com/PennyLaneAI/plugin-test-matrix/pull/43).
I put up a fix for it :)

Fix compatibility with the new Projector class

---

src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

*Issue #, if available:* https://github.com/aws/amazon-braket-pennylane-plugin-python/issues/176
Move code of applying noise_model to circuit translation. Both `execute` and `batch_execute` call circuit translation before running, assuring the noise model is applied to circuits.
unit tests

fix: support noise model in batch_execute

---

src/braket/pennylane_plugin/ops.py
test/unit_tests/test_braket_device.py

In PennLane 0.31, we deprecated the `do_queue` keyword argument, and we are [removing it in 0.32](https://github.com/PennyLaneAI/pennylane/pull/4317). In this PR, I am removing `do_queue` everywhere in preparation for the upcoming release.

Remove `do_queue`

---

.readthedocs.yml

Builds are failing due to missing OS build configuration from the v2 changes. This fixes the issue.
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

fix: add ReadTheDocs build OS changes for v2 in the configuration file

---

src/braket/pennylane_plugin/_version.py
src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

PennyLane master branch for v0.33 has removed the legacy return types system.  `qml.active_return()`, `qml.enable_return()` and `qml.disable_return()` no longer exist.  This causes failures with the braket plugin and master PennyLane that will be released on October 31.
This PR removes references to `active_return`, `enable_return`, and `disable_return`.
Unit tests pass locally.
By submitting this pull request, I confirm that my contribution is made under the terms …

Remove legacy return types system

---

src/braket/pennylane_plugin/braket_device.py

Note: the legacy return types system was actually removed in #210; the commit is named as is to force a minor version change, since this is a deprecation.
This change fixes the legacy return types removal by only converting the forward execution result to a scalar for adjoint gradient computations. This was also the case prior to #210, but the recent change ended up doing this conversion for _all_ forward executions. 
By submitting this pull request, I confirm that my contribution is made under the terms of the …

depr: Remove legacy return types system

---

setup.cfg
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

feat: use measurements getting return types

---

src/braket/pennylane_plugin/braket_device.py

Raise warning when falling back on param-shift

---

setup.cfg

This avoids the two tools (isort and black) from trampling on each other. https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

fix: set the isort profile to black

---

test/unit_tests/test_ahs_device.py

Add noise model to mock aws device in unit test. This is an update for introducing BDK PR https://github.com/amazon-braket/amazon-braket-sdk-python/pull/850
tox

test: Mock only service call in AHS device initialization

---

setup.py

This change more closely reflects what Pennylane version we are targetting.

infra: update Pennylane constraint to be greater than 0.34

---

src/braket/pennylane_plugin/braket_device.py

Fixes: 
```
test/unit_tests/test_braket_device.py::test_bad_statistics
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pennylane/measurements/measurements.py:196: PennyLaneDeprecationWarning: MeasurementProcess.name is deprecated, and will be removed in an upcoming release. To get the name of an observable from a measurement, use MeasurementProcess.obs.name instead
```
By submitting this pull request, I confirm that my contribution is made under …

fix: move to use measurementprocess.obs.name

---

test/unit_tests/test_ahs_device.py

A test for how the AHS device handles operators with undefined diagonalizing gates is failing because it uses `CNOT`, which now does have a definition for diagonalizing gates in PennyLane 0.35.
We update the test to use a `DummyOp` created in the test, that should continue to have undefined diagonalizing gates.

fix: update test to use DummyOp

---

doc/devices/braket_local.rst
doc/devices/braket_remote.rst
src/braket/pennylane_plugin/__init__.py
src/braket/pennylane_plugin/ops.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_ops.py
test/unit_tests/test_translation.py

feat: add phase RX gate

---

src/braket/pennylane_plugin/translation.py
test/unit_tests/test_translation.py

#241 
Add support for `Prod` since Observables made with @ will now be instances of `Prod` instead of `Tensor` in the newest version of PennyLane (0.36.0)
`tox` and `tox -e integ-tests`

feature: support Prod as an observable

---

src/braket/pennylane_plugin/ahs_device.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_translation.py

#245 
- Add support for the new `LinearCombination` as an observable that will be the default in the new version of PennyLane
- Add support for the `qml.opsSProd` and `qml.ops.Sum` in the observable
`tox` and `tox -e integ-tests`

feature: support LinearCombination as observable

---

src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/ops.py
test/unit_tests/test_ahs_device.py
test/unit_tests/test_braket_device.py

The plugin only translates `Hamiltonian`s for the adjoint gradient, but Hamiltonians are often actually `Sum` objects. This change adds `Sum` observable translation.

fix: Translate `Sum` for adjoint gradient

---

doc/devices/braket_remote.rst
src/braket/pennylane_plugin/braket_device.py
test/unit_tests/test_braket_device.py

*Issue #, if available:* closes #255
*Description of changes:* Add persistence of multiple circuits when batch_execute is called
*Testing done:* 

Persist circuits in batch execute

---

setup.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

feat: Support `SProd` and `CompositeOp` for expval

---

src/braket/pennylane_plugin/ahs_device.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_ahs_device.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_translation.py

PennyLane has removed support for legacy operator arithmetic (Hamiltonian, Tensor). These will part of the upcoming release.
Removed tests referring to legacy operator arithmetic. No additional tests needed - we are removing support.

depr: remove legacy opmath

---

setup.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/integ_tests/test_apply.py
test/unit_tests/test_braket_device.py

fix: Flatten observable before getting targets

---

setup.py
src/braket/pennylane_plugin/_version.py
src/braket/pennylane_plugin/braket_device.py
src/braket/pennylane_plugin/translation.py
test/unit_tests/test_braket_device.py
test/unit_tests/test_shadow_expval.py

feat: Program sets
